distillation:
  student_weight: models/yolov8n.pt
  teacher_weight: models/yolov8m.pt
  alpha_init: 0.45
  T_max: 6.00022671881199
  T_min: 2.00042512186827
  warm_epochs: 5
  w_kd: 0.503655840843394
  w_focal: 0.472225371273098
  w_feat: 0
  scale_boost: 2
  focal_gamma: 2
training:
  data_yaml: coco128.yaml
  device: '0'
  epochs: 10
  imgsz: 640
  batch: 16
  workers: 4
  lr0: 0.01
  lrf: 0.1
  warmup_epochs: 3
  mosaic: 0.8
  mixup: 0.1
  close_mosaic: 1
  amp: true
output:
  project: runs/distill
  name: exp2
